app/catalog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("",
         views.ProductHome.as_view(), name="catalog_home"),
    path("results/",
         views.ProductSearchView.as_view(), name="catalog_search"),
    path("product/moderated/",
         views.ProductModeratedListView.as_view(), name="catalog_product_moderated"),
    path("product/<int:pk>/",
         views.ProductView.as_view(), name="catalog_product"),
    path("product/new/",
         views.ProductCreate.as_view(), name="catalog_product_new"),
    path("product/<int:pk>/edit/",
         views.ProductEdit.as_view(), name="catalog_product_edit"),
    path("product/<int:product_id>/publish/",
         views.publish_product_view, name="catalog_publish_product"),
    path("product/<int:product_id>/moderate/",
         views.moderate_product_view, name="catalog_moderate_product"),
    path("category/<int:pk>/",
         views.ProductByCategoryView.as_view(), name="catalog_product_by_category"),
    path("category/",
         views.CategoryView.as_view(), name="catalog_category_list"),
    path("ingredient/",
         views.IngredientListView.as_view(), name="catalog_ingredient_list"),
    path("ingredient/filter/",
         views.filter_ingredients, name="catalog_ingredient_search_filter"),
    path("ingredient/moderated/",
         views.IngredientModeratedListView.as_view(), name="catalog_ingredient_moderated"),
    path("ingredient/<int:pk>/",
         views.ProductByIngredientView.as_view(), name="catalog_ingredient"),
    path("ingredient/<int:ingredient_id>/publish/",
         views.publish_ingredient_view, name="catalog_publish_ingredient"),
    path("tag/<slug:tagslug>/",
         views.ProductByTagView.as_view(), name="catalog_product_by_tag"),
    path("tag/",
         views.TagView.as_view(), name="catalog_tag_list"),
    path("manufacturer/",
         views.ManufacturerView.as_view(), name="catalog_manufacturer_list"),
    path("manufacturer/<int:pk>/",
         views.ProductByManufacturer.as_view(), name="catalog_product_by_manufacturer"),
    path("owner/<int:pk>/",
         views.ProductOwnerListView.as_view(), name="catalog_product_by_owner"),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

app/stats/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path("",
         views.dashboard, name="stats_home"),
    path("json/",
         views.dashboard_json, name="stats_json"),
]

app/catalog/models.py
from datetime import date
from django.contrib.auth.models import Group
from django.contrib.contenttypes.fields import GenericRelation
from django.db.models import Q, ExpressionWrapper, BooleanField
from django.utils import timezone
from django_fsm import FSMField, transition
from star_ratings.models import Rating

from accounts.models import Profile
from django.db import models
from filer.fields.image import FilerImageField
from taggit.managers import TaggableManager

from membership.models import Membership


class AutoDateTimeField(models.DateTimeField):
    def pre_save(self, model_instance, add):
        return timezone.now()


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=50, unique=True)
    url = models.URLField(blank=True)
    address1 = models.CharField(max_length=50, blank=True)
    address2 = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=40, blank=True)
    country = models.CharField(max_length=40, blank=True)

    def __str__(self):
        return self.name


def can_approve(instance, user):
    return user.is_superuser or user.is_staff


def can_publish(instance, user):
    return user.member.has_role('publisher')


def is_moderated(instance, user):
    return user.member.has_role('moderated')


def can_delete(instance, user):
    return can_approve(instance=instance, user=user)


def is_product_editor(instance, user):
    if not user.is_authenticated:
        return False
    if user.member.has_role('product_editor'):
        return True
    if can_approve(instance=instance, user=user):
        return True
    return False


def get_ingredients(query, limit=10):
    ingredient_list = Ingredient.objects.filter(name__icontains=query).distinct()[:limit]
    alt_name_list = Ingredient.objects.filter(altname__name__icontains=query).distinct()[:limit]
    # we can merge query sets of same object https://docs.djangoproject.com/en/3.0/ref/models/querysets/#or
    ingredients = ingredient_list | alt_name_list
    return ingredients


# get_altnames_by_ingredient_id:
# returns a list of { ingredient_id, name } where name is altname or ingredient.name
def get_ingredient_search_results(query, limit=10):
    # Encapsulate the comparison expression.
    expression = Q(name__startswith=query)
    # Wrap the expression to specify the field type.
    is_match = ExpressionWrapper(expression, output_field=BooleanField())

    # Annotate each object with the comparison.
    # data = ingredients.annotate(my_field=is_match)
    # Order by the annotated field in reverse, so `True` is first (0 < 1).
    # data = data.order_by('-my_field')

    ingredients = Ingredient.objects.filter(name__icontains=query)\
        .values_list('pk', 'name').annotate(close=is_match).order_by('-close')[:limit]
    alt_names = Altname.objects.filter(name__icontains=query)\
        .values_list('ingredient_id', 'name').annotate(close=is_match).order_by('-close')[:limit]

    ingredient_list = [
        dict(pk=v[0], name=v[1])
        for v
        in ingredients
    ]
    alt_names_list = [
        dict(pk=v[0], name=v[1])
        for v
        in alt_names
    ]
    return ingredient_list + alt_names_list


class Ingredient(models.Model):
    name = models.CharField(max_length=70, unique=True)
    description = models.TextField(max_length=1023, blank=True)
    state = FSMField(default='new', protected=True)
    created_at = models.DateField(default=timezone.now)
    updated_at = AutoDateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    @transition(field=state, source='new', target='published', permission=can_publish)
    def publish(self):
        pass

    @transition(field=state, source='*', target='moderated')
    def moderate(self):
        pass

    @transition(field=state, source='moderated', target='published',
                permission=can_approve)
    def approve(self):
        pass

    @transition(field=state, source='*', target='deleted', permission=can_delete)
    def remove(self):
        pass


class Altname(models.Model):
    name = models.CharField(max_length=70, unique=True)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name='altname')

    def __str__(self):
        return self.name


def get_default_image():
    from filer.models.imagemodels import Image
    try:
        return Image.objects.filter(name='Default Image').order_by('-uploaded_at')[0].pk
    except IndexError:
        return None


class Product(models.Model):
    name = models.CharField(max_length=70, unique=True)
    description = models.TextField(max_length=1023, blank=True)
    image = FilerImageField(on_delete=models.CASCADE, null=True, blank=True,
                            default=get_default_image, related_name='product_image')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    views = models.PositiveIntegerField(default=0)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, related_name='products')
    ingredients = models.ManyToManyField('Ingredient')
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, related_name='products')
    group = models.ForeignKey(Group, on_delete=models.PROTECT, null=True, related_name='products')
    ratings = GenericRelation(Rating, related_query_name='products')
    state = FSMField(default='new', protected=True)
    created_at = models.DateField(default=timezone.now)
    updated_at = AutoDateTimeField(default=timezone.now)
    tags = TaggableManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('catalog_product', args=[str(self.id)])

    @transition(field=state, source='new', target='published', permission=can_publish)
    def publish(self):
        pass

    @transition(field=state, source='*', target='moderated')
    def moderate(self):
        pass

    @transition(field=state, source='moderated', target='published',
                permission=can_approve)
    def approve(self):
        pass

    @transition(field=state, source='*', target='deleted', permission=can_delete)
    def remove(self):
        pass


class BuyLink(models.Model):
    class LinkType(models.TextChoices):
        OFFICIAL = 'Official', 'Official'
        AMAZON = 'Amazon', 'Amazon'
        EBAY = 'eBay', 'eBay'
        OTHER = 'Other', 'Other'

    name = models.CharField(
        max_length=50,
        choices=LinkType.choices,
        default=LinkType.OFFICIAL
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='links')
    url = models.URLField(unique=True)
    clicks = models.PositiveIntegerField(default=0)
    rating = models.FloatField(default=0.0)

    def __str__(self):
        return self.product.name + " " + self.name


class Search(models.Model):
    q = models.CharField(max_length=30)
    date = models.DateField(default=date.today)
    count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.q

app/catalog/forms.py
from django import forms

from catalog.models import Search, Product
from catalog.widgets import SearchableSelect


class SearchForm(forms.ModelForm):
    class Meta:
        model = Search
        fields = ['q', ]
        labels = {
             'q': ''
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('owner', 'group', 'state', 'views')
        widgets = {
            'ingredients': SearchableSelect(
                model='catalog.Ingredient',
                template_name='catalog/widget/ingredient_select.html',
                many=True,
                limit=10)
        }

app/catalog/views/errors.py
# Error Pages
from django.shortcuts import render


def server_error(request):
    return render(request, 'errors/500.html')


def not_found(request, exception):
    return render(request, 'errors/404.html', status=404)


def permission_denied(request, exception):
    return render(request, 'errors/403.html', status=403)


def bad_request(request, exception):
    return render(request, 'errors/400.html', status=400)

app/catalog/views/ingredient.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django_fsm import can_proceed

from catalog.models import Product, Ingredient, get_ingredient_search_results


def filter_ingredients(request):
    value = request.GET.get('q')
    limit = int(request.GET.get('limit', 10))

    values = get_ingredient_search_results(value, limit)
    return JsonResponse(dict(result=values))


class IngredientListView(ListView):
    model = Ingredient
    context_object_name = 'ingredients'
    template_name = 'catalog/ingredient_list.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return Ingredient.objects.all().order_by('-name')


class IngredientModeratedListView(UserPassesTestMixin, ListView):
    model = Ingredient
    context_object_name = 'ingredients'
    template_name = 'catalog/ingredient_list.html'
    paginate_by = 20

    def get_queryset(self):
        return Ingredient.objects.all().filter(state='moderated').order_by('-name') | \
               Ingredient.objects.all().filter(state='new').order_by('-name')

    def test_func(self):
        return self.request.user.is_staff


class IngredientView(DetailView):
    model = Ingredient
    template_name = 'catalog/ingredient_full.html'


def publish_ingredient_view(request, ingredient_id):
    ingredient = get_object_or_404(Ingredient, pk=ingredient_id)
    if not can_proceed(ingredient.publish):
        messages.info(request, "Access Denied")
        return redirect('catalog_ingredient', ingredient.pk)

    ingredient.publish()
    ingredient.save()
    messages.info(request, "Ingredient Published")
    return redirect('catalog_ingredient', ingredient.pk)


class ProductByIngredientView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'catalog/ingredient_full.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        kwargs['ingredient'] = self.ingredient
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.ingredient = get_object_or_404(Ingredient, pk=self.kwargs.get('pk'))
        queryset = self.ingredient.product_set.filter(state='published').order_by('-name')
        return queryset

app/catalog/views/lists.py
from django.db.models import Count
from django.views.generic import ListView
from taggit.models import Tag

from catalog.models import Category, Manufacturer


class CategoryView(ListView):
    model = Category
    context_object_name = 'categories'
    template_name = 'catalog/category_list.html'
    paginate_by = 20

    def get_queryset(self):
        return Category.objects.all().order_by('-name')


class ManufacturerView(ListView):
    model = Manufacturer
    context_object_name = 'manufacturers'
    template_name = 'catalog/manufacturer_list.html'
    paginate_by = 20

    def get_queryset(self):
        return Manufacturer.objects.all().order_by('-name')


class TagView(ListView):
    model = Tag
    context_object_name = 'tags'
    template_name = 'catalog/tag_list.html'
    paginate_by = 20

    def get_queryset(self):
        queryset = Tag.objects.all().order_by('-name')
        queryset2 = queryset.annotate(num_times=Count('taggit_taggeditem_items'))
        return queryset2

app/catalog/templates/catalog/category_list.html
{% extends "base.html" %}
{% load humanize %}
{% load bootstrap4 %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'catalog_home' %}">Search</a></li>
    <li class="breadcrumb-item active">Categories</li>
{% endblock %}

{% block page_content %}
    {% if page_obj %}
    <table class="table table-striped mb-4">
    <thead class="thead-inverse">
      <tr>
        <th>Category</th>
        <th>Products</th>
      </tr>
    </thead>
    <tbody>
      {% for category in page_obj %}
      {% url 'catalog_product_by_category' category.pk as category_url %}
        <tr>
          <td><a href="{{ category_url }}">{{ category.name }}</a></td>
          <td>{{ category.products.count }}</td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
      {% if is_paginated %}
      {% bootstrap_pagination page_obj %}
      {% endif %}
    {% else %}
        <p>No categories found.</p>
    {% endif %}
{% endblock %}

app/catalog/templates/catalog/home.html
{% extends 'catalog/product_detail_list.html' %}
{% load bootstrap4 %}
{% block title %}
 {{ search.name }} - {{ block.super }}
{% endblock %}

{% block content_intro %}
    <div class="mx-4">
      <p>Make informed decisions about your skin care products.</p>
      <p>We list ingredients with helpful information about each one so you know what you are putting on your skin.</p>
      <p>The newest products are listed below. Search is available by typing in the box above.</p>
    </div>
{% endblock %}

app/catalog/templates/catalog/ingredient_full.html
{% extends 'catalog/product_list.html' %}
{% load bootstrap4 %}

{% block title %}
 {{ ingredient.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'catalog_home' %}">Search</a></li>
    <li class="breadcrumb-item"><a href="{% url 'catalog_ingredient_list' %}">Ingredient List</a></li>
    <li class="breadcrumb-item active">{{ ingredient.name }}</li>
{% endblock %}

{% block content_intro %}
    <p><h3>{{ ingredient.name }}</h3></p>
    <p>
        {% if ingredient.state == 'published' or user.is_authenticated and user.is_staff %}
        <strong>Description:</strong>
        {{ ingredient.description|escape }}
    {% endif %}
    &nbsp;</p>
    {% if ingredient.state != 'published' and user.is_authenticated and user.is_staff %}
        <a href="{% url 'catalog_publish_ingredient' ingredient.pk %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Publish</a>
    {% endif %}
    {% if ingredient.altname.all.count > 0 %}
    <p><strong>Alternative names:</strong> {% for altname in ingredient.altname.all %}{{ altname.name }}{% if forloop.last %} {% else %}, {% endif %}{% endfor %}</p>
    {% endif %}
{% endblock %}

app/catalog/templates/catalog/ingredient_list.html
{% extends "base.html" %}
{% load humanize %}
{% load bootstrap4 %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'catalog_home' %}">Search</a></li>
    <li class="breadcrumb-item">Ingredient List</li>
{% endblock %}

{% block page_content %}
    {% if page_obj %}
    <table class="table table-striped mb-4">
    <thead class="thead-inverse">
      <tr>
        <th>Ingredient</th>
        <th>Products</th>
      </tr>
    </thead>
    <tbody>
      {% for ingredient in page_obj %}
        <tr>
          <td>
              {% if user.is_staff %}{% if ingredient.state != 'published' %}<span class="badge badge-secondary">Mod</span>{% endif %}{% endif %}
              <a href="{% url 'catalog_ingredient' ingredient.pk %}">{{ ingredient.name }}</a></td>
          <td>{{ ingredient.product_set.count }}</td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
      {% if is_paginated %}
      {% bootstrap_pagination page_obj %}
      {% endif %}
    {% else %}
        <p>No ingredients found.</p>
    {% endif %}
{% endblock %}

app/catalog/templates/catalog/manufacturer_list.html
{% extends "base.html" %}
{% load humanize %}
{% load bootstrap4 %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'catalog_home' %}">Search</a></li>
    <li class="breadcrumb-item active">Manufacturers</li>
{% endblock %}

{% block page_content %}
    {% if page_obj %}
    <table class="table table-striped mb-4">
    <thead class="thead-inverse">
      <tr>
        <th>Manufacturer</th>
        <th>Products</th>
      </tr>
    </thead>
    <tbody>
      {% for manufacturer in page_obj %}
      {% url 'catalog_product_by_manufacturer' manufacturer.pk as manufacturer_url %}
        <tr>
          <td><a href="{{ manufacturer_url }}">{{ manufacturer.name }}</a></td>
          <td>{{ manufacturer.products.count }}</td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
      {% if is_paginated %}
      {% bootstrap_pagination page_obj %}
      {% endif %}
    {% else %}
        <p>No categories found.</p>
    {% endif %}
{% endblock %}

app/catalog/templates/catalog/privacy.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'catalog_home' %}">Search</a></li>
    <li class="breadcrumb-item active">Privacy Policy</li>
{% endblock %}

{% block page_content %}
    <h2>Data Protection and Privacy</h2>
    <p>Some services on this website require us to collect personal information from you.
        To comply with the Data Protection Act, we have a duty to tell you how we store the information we collect
        and how it is used. Any information you do submit will be stored securely and will never be passed on or sold
        to any third party.</p>
    <h2>User anonymity and personal information</h2>
    <p>Log files are maintained and analysed of all requests for files on this website's web servers.
        Log files do not capture personal information but do capture the user's IP address, which is automatically
        recognised by our web servers.</p>
    <p>Aggregated analysis of these log files is used to monitor website usage. These analyses may be made available
        to our staff and partner agencies to allow them to measure, for example, overall popularity of the site and
        typical user paths through the site.</p>
    <p>Except as stated already, we will make no attempt to identify individual users. You should be aware, however,
        that access to web pages will generally create log entries in the systems of your ISP or
        network service provider. These entities may be in a position to identify the client computer equipment used
        to access a page. Such monitoring would be done by the provider of network services and
        is beyond the responsibility or control of us.</p>
    <p>We will make no attempt to track or identify individual users, except where there is a reasonable suspicion
        that unauthorised access to systems is being attempted. In the case of all users, we reserves the right to
        attempt to identify and track any individual who is reasonably suspected of trying to gain unauthorised access
        to computer systems or resources operating as part of our web services.</p>
    <p>As a condition of use of this site, all users must give permission for us to use its access logs to attempt
        to track users who are reasonably suspected of gaining, or attempting to gain, unauthorised access.</p>
    <p>All log file information collected by us is kept secure and no access to raw log files is given to any third party.</p>
    <h2>Use of cookies</h2>
    <p>This website does not store any information that would, on its own, allow us to identify individual users
        of this service without their permission. Any cookies that may be used by this website are used either solely
        on a per session basis or to maintain user preferences. Cookies are not shared with any third parties.</p>
    <table class="table">
	  <thead>
		<tr>
			<th scope="col"><span style="font-weight: 400;">Cookie Name</span></th>
			<th scope="col"><span style="font-weight: 400;">Description</span></th>
		</tr>
	  </thead>
	  <tbody>
		<tr>
			<td data-th="Cookie Name">session, sessionid</td>
			<td data-th="Cookie Description">
			<p>This is a simple token used by the applications to identify your unique session on the website.
                Typically used to maintain the integrity of your session while transacting information with a website
                (accessing secure areas, forms submissions etc)</p>
			</td>
		</tr>
		<tr>
			<td data-th="Cookie Name">CookieControl</td>
			<td data-th="Cookie Description">
			<p>Cookie Control cookies. This cookie is set in order to remember the user's preferences in regards to cookies.</p>
			</td>
		</tr>
		<tr>
			<td data-th="Cookie Name">euconsent</td>
			<td data-th="Cookie Description">
			  <p>This cookie contains the IAB TCF consent string and consent information for all the standard IAB vendors and purposes.</p>
			</td>
		</tr>
		<tr>
			<td data-th="Cookie Name">__utma, __utmb, __utmc, __utmc, _ga, _gat, _gid</td>
			<td data-th="Cookie Description">
			  <p>Google Analytics: We use Google Analytics to monitor traffic levels, search queries and visits to this website.</p>
              <p>Google Analytics stores IP address anonymously on its servers in the US, and neither us or
                  Google associate your IP address with any personally identifiable information.</p>
              <p>These cookies enable Google to determine whether you are a return visitor to the site,
                  and to track the pages that you visit during your session.</p>
  			  <p>These cookies are set only after the user has given consent to us to use cookies.</p>
			</td>
		</tr>
		<tr>
			<td data-th="Cookie Name">1P_JAR, AID, ANID, APISID, DSID, DV, HSID, NID, SAPISID, SID, SSID, _fbp, id</td>
			<td data-th="Cookie Description">
			<p>Google and Doubleclick remarketing cookies. We use these cookies to help us improve the relevancy of
                advertising campaigns you receive.</p>
			<p>These cookies are set only after the user has given consent to us to use cookies.</p>
			</td>
		</tr>
	  </tbody>
    </table>
{% endblock %}

app/catalog/templates/catalog/product_by_category.html
{% extends 'catalog/product_list.html' %}
{% load bootstrap4 %}
{% block title %}
 {{ category.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'catalog_category_list' %}">Categories</a></li>
    <li class="breadcrumb-item active">{{ category.name }}</li>
{% endblock %}

{% block content_intro %}
{% endblock %}

app/catalog/templates/catalog/product_by_manufacturer.html
{% extends 'catalog/product_list.html' %}
{% load bootstrap4 %}
{% block title %}
 {{ manufacturer.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'catalog_manufacturer_list' %}">Manufacturer</a></li>
    <li class="breadcrumb-item active">{{ manufacturer.name }}</li>
{% endblock %}

{% block content_intro %}
{% endblock %}

app/catalog/templates/catalog/product_by_tag.html
{% extends 'catalog/product_list.html' %}
{% load bootstrap4 %}
{% block title %}
 {{ category.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'catalog_home' %}">Search</a></li>
    <li class="breadcrumb-item"><a href="{% url 'catalog_tag_list' %}">Tags</a></li>
    <li class="breadcrumb-item active">{{ tag }}</li>
{% endblock %}

{% block content_intro %}
    <p>Listing products tagged with <span class="badge badge-pill badge-info">{{ tag }}</span></p>
{% endblock %}

app/catalog/templates/catalog/product_detail_list.html
{% extends "base.html" %}
{% load humanize %}
{% load has_role %}
{% load bootstrap4 %}
{% load thumbnail %}
{% load class_tag %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Product List</li>
{% endblock %}

{% block page_content %}
    {% block content_intro %}
    {% endblock content_intro %}
    {% if page_obj %}
    <table class="table table-sm table-striped mb-4">
    <thead class="thead-inverse">
      <tr>
        <th>Name</th>
        <th>Info</th>
      </tr>
    </thead>
    <tbody>
      {% for product in page_obj %}
        {% if product|get_class == 'Product' %}
            {% url 'catalog_product' product.pk as product_url %}
          {% else %}
            {% url 'catalog_ingredient' product.pk as product_url %}
          {% endif %}
        <tr data-href="{{ product_url }}">
          <td>
              <h5>{{ product.name }}</h5><br/>
          <img alt="{{ product.name }}" src="{% thumbnail product.image 75x0 crop %}">
          </td>
          <td>
            {{ product.description|truncatewords:20 }}<br/>
              {% for ingredient in product.ingredients.all %} <span class="badge badge-pill badge-info">{{ ingredient.name }}</span> {% endfor %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
      {% if is_paginated %}
      {% bootstrap_pagination page_obj %}
      {% endif %}
    {% else %}
        <p class="text-center my-4">No Products found for that query.</p>
    {% endif %}
{% endblock %}

{% block javascript %}
    <script>
        jQuery(document).ready(function($) {
            $('*[data-href]').on('click', function() {
                window.location = $(this).data("href");
            });
        });
</script>
{% endblock %}

app/catalog/templates/catalog/rating_widget.html
{% extends "star_ratings/widget_base.html" %}
{% block rating_detail %}
    <div class="star-ratings-rating-average">
        <span class='star-ratings-rating-value'>{{ rating.average|floatformat:"-2" }}</span> | <span class='star-ratings-rating-value'>{{ rating.count }}</span> Reviews
    </div>
    <div class="star-ratings-rating-user">
        You Rated: <span class='star-ratings-rating-value'>{% if user_rating %}{{ user_rating.score }}{% else %}Not rated{% endif %}</span>
    </div>
    {% if not user.is_authenticated and not anonymous_ratings and not read_only %}
        <p>Please log in to rate.</p>
    {% endif %}

{% endblock %}

app/catalog/templates/catalog/search_products.html
{% extends 'catalog/product_list.html' %}
{% load bootstrap4 %}
{% block title %}
 {{ search.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'catalog_search' %}">Search</a></li>
  <li class="breadcrumb-item active">{{ search.name }}</li>
{% endblock %}

{% block content_intro %}
    <div class="mx-4">
      <p>Make informed decisions about your skin care products.</p>
      <p>We list ingredients with helpful information about each one so you know what you are putting on your skin.</p>
    </div>
    <div class="mx-auto pt-4" style="width: 60%;">
    <h5>Search for a product or ingredient</h5>
      <form action="{% url 'catalog_search' %}" method="get" novalidate>
    {%  bootstrap_form form %}
          <div class="mx-auto pb-2" style="width: 100px;">
            <button type="submit" class="btn btn-block btn-success">Search</button>
          </div>
      </form>
    </div>
{% endblock %}