app/stats/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path("",
         views.dashboard, name="stats_home"),
    path("json/",
         views.dashboard_json, name="stats_json"),
]

app/catalog/models.py
from datetime import date
from django.contrib.auth.models import Group
from django.contrib.contenttypes.fields import GenericRelation
from django.db.models import Q, ExpressionWrapper, BooleanField
from django.utils import timezone
from django_fsm import FSMField, transition
from star_ratings.models import Rating

from accounts.models import Profile
from django.db import models
from filer.fields.image import FilerImageField
from taggit.managers import TaggableManager

from membership.models import Membership


class AutoDateTimeField(models.DateTimeField):
    def pre_save(self, model_instance, add):
        return timezone.now()


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=50, unique=True)
    url = models.URLField(blank=True)
    address1 = models.CharField(max_length=50, blank=True)
    address2 = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=40, blank=True)
    country = models.CharField(max_length=40, blank=True)

    def __str__(self):
        return self.name


def can_approve(instance, user):
    return user.is_superuser or user.is_staff


def can_publish(instance, user):
    return user.member.has_role('publisher')


def is_moderated(instance, user):
    return user.member.has_role('moderated')


def can_delete(instance, user):
    return can_approve(instance=instance, user=user)


def is_product_editor(instance, user):
    if not user.is_authenticated:
        return False
    if user.member.has_role('product_editor'):
        return True
    if can_approve(instance=instance, user=user):
        return True
    return False


def get_ingredients(query, limit=10):
    ingredient_list = Ingredient.objects.filter(name__icontains=query).distinct()[:limit]
    alt_name_list = Ingredient.objects.filter(altname__name__icontains=query).distinct()[:limit]
    # we can merge query sets of same object https://docs.djangoproject.com/en/3.0/ref/models/querysets/#or
    ingredients = ingredient_list | alt_name_list
    return ingredients


# get_altnames_by_ingredient_id:
# returns a list of { ingredient_id, name } where name is altname or ingredient.name
def get_ingredient_search_results(query, limit=10):
    # Encapsulate the comparison expression.
    expression = Q(name__startswith=query)
    # Wrap the expression to specify the field type.
    is_match = ExpressionWrapper(expression, output_field=BooleanField())

    # Annotate each object with the comparison.
    # data = ingredients.annotate(my_field=is_match)
    # Order by the annotated field in reverse, so `True` is first (0 < 1).
    # data = data.order_by('-my_field')

    ingredients = Ingredient.objects.filter(name__icontains=query)\
        .values_list('pk', 'name').annotate(close=is_match).order_by('-close')[:limit]
    alt_names = Altname.objects.filter(name__icontains=query)\
        .values_list('ingredient_id', 'name').annotate(close=is_match).order_by('-close')[:limit]

    ingredient_list = [
        dict(pk=v[0], name=v[1])
        for v
        in ingredients
    ]
    alt_names_list = [
        dict(pk=v[0], name=v[1])
        for v
        in alt_names
    ]
    return ingredient_list + alt_names_list


class Ingredient(models.Model):
    name = models.CharField(max_length=70, unique=True)
    description = models.TextField(max_length=1023, blank=True)
    state = FSMField(default='new', protected=True)
    created_at = models.DateField(default=timezone.now)
    updated_at = AutoDateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    @transition(field=state, source='new', target='published', permission=can_publish)
    def publish(self):
        pass

    @transition(field=state, source='*', target='moderated')
    def moderate(self):
        pass

    @transition(field=state, source='moderated', target='published',
                permission=can_approve)
    def approve(self):
        pass

    @transition(field=state, source='*', target='deleted', permission=can_delete)
    def remove(self):
        pass


class Altname(models.Model):
    name = models.CharField(max_length=70, unique=True)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name='altname')

    def __str__(self):
        return self.name


def get_default_image():
    from filer.models.imagemodels import Image
    try:
        return Image.objects.filter(name='Default Image').order_by('-uploaded_at')[0].pk
    except IndexError:
        return None


class Product(models.Model):
    name = models.CharField(max_length=70, unique=True)
    description = models.TextField(max_length=1023, blank=True)
    image = FilerImageField(on_delete=models.CASCADE, null=True, blank=True,
                            default=get_default_image, related_name='product_image')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    views = models.PositiveIntegerField(default=0)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, related_name='products')
    ingredients = models.ManyToManyField('Ingredient')
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, related_name='products')
    group = models.ForeignKey(Group, on_delete=models.PROTECT, null=True, related_name='products')
    ratings = GenericRelation(Rating, related_query_name='products')
    state = FSMField(default='new', protected=True)
    created_at = models.DateField(default=timezone.now)
    updated_at = AutoDateTimeField(default=timezone.now)
    tags = TaggableManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('catalog_product', args=[str(self.id)])

    @transition(field=state, source='new', target='published', permission=can_publish)
    def publish(self):
        pass

    @transition(field=state, source='*', target='moderated')
    def moderate(self):
        pass

    @transition(field=state, source='moderated', target='published',
                permission=can_approve)
    def approve(self):
        pass

    @transition(field=state, source='*', target='deleted', permission=can_delete)
    def remove(self):
        pass


class BuyLink(models.Model):
    class LinkType(models.TextChoices):
        OFFICIAL = 'Official', 'Official'
        AMAZON = 'Amazon', 'Amazon'
        EBAY = 'eBay', 'eBay'
        OTHER = 'Other', 'Other'

    name = models.CharField(
        max_length=50,
        choices=LinkType.choices,
        default=LinkType.OFFICIAL
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='links')
    url = models.URLField(unique=True)
    clicks = models.PositiveIntegerField(default=0)
    rating = models.FloatField(default=0.0)

    def __str__(self):
        return self.product.name + " " + self.name


class Search(models.Model):
    q = models.CharField(max_length=30)
    date = models.DateField(default=date.today)
    count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.q

app/catalog/views/errors.py
# Error Pages
from django.shortcuts import render


def server_error(request):
    return render(request, 'errors/500.html')


def not_found(request, exception):
    return render(request, 'errors/404.html', status=404)


def permission_denied(request, exception):
    return render(request, 'errors/403.html', status=403)


def bad_request(request, exception):
    return render(request, 'errors/400.html', status=400)

app/templates/403_csrf.html
{% extends 'error.html' %}
{% load bootstrap4 %}

{% block card_body %}
    <div class="alert alert-warning" role="alert">CSRF protection error, please check your cookie settings.</div>
{% endblock card_body %}

app/templates/base.html
{% load static %}{% load bootstrap4 %}{% load analytical %}{% load version %}<!DOCTYPE html>
<html lang="en">
<head>
    {% analytical_head_top %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device=width, inital-scale=1, shrink-to-fit=no">
    {% bootstrap_css %}
    {% block stylesheet %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link href="/static/filer/css/admin_filer.css" type="text/css" media="all" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Exo:wght@100&display=swap" rel="stylesheet">
    <title>{% block title %}Skin Catalog{% endblock title %}</title>
    {% analytical_head_bottom %}
</head>
<body class="bg-dark">
{% analytical_body_top %}
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container bg-dark rounded">
        <a class="navbar-brand font-primary ml-2" href="{% url 'catalog_home' %}">Skin Catalog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse pl-2 bg-dark" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item{% if request.resolver_match.url_name == "catalog_home" %} active{% endif %}">
                    <a class="nav-link" href="{% url 'catalog_home' %}">Home</a>
                </li>
                <li class="nav-item{% if request.resolver_match.url_name == "board_home" %} active{% endif %}">
                    <a class="nav-link" href="{% url 'board_home' %}">Support</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Blog</a>
                </li>
            </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'catalog_search' %}" method="get" novalidate>
          <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" maxlength="30" id="id_q">
          <button class="btn btn-outline-success my-2" type="submit"><i class="fa fa-search"></i></button>
        </form>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                            {% if user.is_staff %}
                                <a class="dropdown-item" href="{% url 'stats_home' %}">Dashboard</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'my_account' %}">My Account</a>
                            <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                            <div class="drowdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    <form class="form-inline ml-auto my-2">
                    <a href="{% url 'login' %}" class="btn btn-outline-light ml-2 font-primary">Login</a>
                    <a href="{% url 'register' %}" class="btn btn-success mx-2 font-primary">Register</a>
                    </form>
                {% endif %}
            </ul>
        </div>
    </div>

</nav>

{# body overrides all this default stuff #}
{% block body %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<div class="container bg-light rounded py-2">
<ol class="breadcrumb my-4">
    {% block breadcrumb %}
    {% endblock %}
</ol>
    {% block page_content %}{% endblock %}
</div>

{% endblock body %}
<span class='version'>Version: {% version %}</span>
{% bootstrap_javascript jquery='full' %}
{% include "includes/cookie_control.html" %}
{% block javascript %}{% endblock %}
{% analytical_body_bottom %}
</body>
</html>

app/templates/error.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 col-sm-8">
                <div class="card">
                    <div class="card-body">
                        {% block card_body %}{% endblock card_body %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}